name: Trigger CI Build

on:
  issue_comment:
    types: [created]

jobs:
  build-branch:

    runs-on: ubuntu-latest

    if: contains(github.event.comment.body, '/build')

    steps:
      - name: Trigger CI Build
        uses: henrich-m/trigger-ci@v0.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
